AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CodeCommit repository with lambda trigger

Parameters:
  RepoName:
    Description: Repository name
    Type: String

Resources:
  # private CodeCommit repository
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: This is a repository for the webApp build

