AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CodeCommit repository with lambda trigger

Parameters:
  RepoName:
    Description: Repository name
    Type: String
  S3BucketName:
    Description: Destination Bucket
    Type: String

Resources:
  # private CodeCommit repository
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: This is a repository for the webApp build

  # copy files to bucket function
  ReplicateFilesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/
      Handler: ReplicateFiles.handler
      Runtime: nodejs16.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          DestinationBucketName: !Ref S3BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - CodeCommitReadPolicy:
            RepositoryName: !GetAtt CodeCommitRepo.Name
      Events:
        CodeCommitEvent: 
          Type: CloudWatchEvent
          Properties:
            Target:
              Id: !Ref LambdaRule
            Pattern:
              detail:
                event:
                  - referenceUpdated

  # Role for the event
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            - Effect: Allow
              Principal:
                  Service:
                    - events.amazonaws.com
              Action:
                - sts:AssumeRole
      Description: !Sub IAM Role for ${AWS::StackName}
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - lambda:InvokeFunction
                Effect: Allow
                Resource: !GetAtt ReplicateFilesFunction.Arn

  # Event that triggers the Lambda when the content of a CodeCommit repository is modified 
  LambdaRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        detail:
          event:
            - referenceUpdated
      State: ENABLED
      RoleArn: !GetAtt LambdaRole.Arn
