AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CodeCommit repository with lambda trigger

Parameters:
  RepoName:
    Description: Repository name
    Type: String
  S3BucketName:
    Description: Destination Bucket
    Type: String

Resources:
  # copy files to bucket function
  ReplicateFilesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/
      Handler: ReplicateFiles.handler
      Runtime: nodejs16.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          DestinationBucketName: !Ref S3BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - CodeCommitReadPolicy:
            RepositoryName: !GetAtt CodeCommitRepo.Name
      

  # private CodeCommit repository
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: This is a repository for the webApp build

