AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket fronted by Cloudfront distribution

Parameters:
  PageDomain:
    Type: String
    Description: page domain for build stored into s3

Resources:
  # private s3 bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Bucket for the builds
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
    DeletionPolicy: Retain
  
  # CloudFront distribution origin access identity to connece with S3 bucket
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for s3

  # CloudFront Distribution
  PublicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: S3-build-bucket
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        Comment: CloudFront distribution
        DefaultCacheBehavior:
          DefaultTTL: 86400
          MaxTTL: 31536000
          TargetOriginId: !Sub 'S3-${AWS::StackName}-root'
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3-build-bucket
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
        PriceClass: 'PriceClass_200'

  # Policy to enable public read
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: 
              !Sub
                - ${bucketArn}/*
                - bucketArn: !GetAtt S3Bucket.Arn
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

Outputs:
  S3PrivateBucketArn:
    Description: Website bucket locator
    Value: !GetAtt S3Bucket.Arn
  S3PrivateBucketName:
    Description: Website bucket name
    Value: !GetAtt S3Bucket.DomainName
  PublicDistributionDomain:
    Description: CloudFront distribution
    Value: !GetAtt PublicDistribution.DomainName